#!/usr/bin/env python3
"""KWhale one-command installer.

Usage:
    curl -fsSL https://raw.githubusercontent.com/Atte149/kwhale/main/install.py | python3 -
    python3 install.py [--non-interactive] [--data-root PATH] [--repo URL] [--branch BRANCH]

Clones the KWhale server repo, generates all .env files consistently, creates
data directories and external Docker networks, builds and starts the stack,
waits for healthchecks, and prints the API token + next steps.
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import shutil
import subprocess
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path

DEFAULT_REPO = "https://github.com/Atte149/kwhale.git"
DEFAULT_BRANCH = "main"
DEFAULT_DATA_ROOT = "./kwhale-data"
INSTALL_DIR_NAME = "kwhale"

EXTERNAL_NETWORKS = ["caddy_default", "singbox_net"]

HEALTH_ENDPOINTS = {
    "api": ("http://127.0.0.1:{api_port}/healthz", 200),
    "navidrome": ("http://127.0.0.1:{navidrome_port}/rest/ping.view", 200),
}


# ───────────────────────── helpers ─────────────────────────


def _docker_needs_sudo() -> bool:
    """Detect if docker commands require sudo on this host."""
    r = subprocess.run(["docker", "info"], capture_output=True)
    return r.returncode != 0


SUDO: list[str] = ["sudo"] if _docker_needs_sudo() else []


def run(cmd: list[str], cwd: Path | None = None, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    """Run a command, streaming output unless capture=True. Auto-prefixes sudo for docker."""
    # Auto-add sudo for docker commands if needed
    if cmd and cmd[0] == "docker" and SUDO:
        cmd = SUDO + cmd
    if capture:
        return subprocess.run(cmd, cwd=cwd, check=check, capture_output=True, text=True)
    return subprocess.run(cmd, cwd=cwd, check=check, text=True)


def prompt(msg: str, default: str = "", password: bool = False) -> str:
    """Interactive prompt with default fallback."""
    if password:
        import getpass
        val = getpass.getpass(f"{msg} [{'*' * len(default) if default else ''}]: ")
    else:
        suffix = f" [{default}]" if default else ""
        val = input(f"{msg}{suffix}: ").strip()
    return val or default


def confirm(msg: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    val = input(f"{msg} [{hint}]: ").strip().lower()
    if not val:
        return default
    return val in ("y", "yes", "1", "true")


def header(text: str) -> None:
    print(f"\n{'=' * 60}\n  {text}\n{'=' * 60}")


def info(msg: str) -> None:
    print(f"  [+] {msg}")


def warn(msg: str) -> None:
    print(f"  [!] {msg}")


def err(msg: str) -> None:
    print(f"  [x] {msg}", file=sys.stderr)


def http_get(url: str, timeout: int = 10) -> int:
    try:
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status
    except urllib.error.HTTPError as e:
        return e.code
    except Exception:
        return 0


def http_post_json(url: str, data: dict, timeout: int = 10) -> dict | None:
    try:
        body = json.dumps(data).encode()
        req = urllib.request.Request(
            url, data=body, headers={"Content-Type": "application/json"}, method="POST"
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read())
    except Exception:
        return None


# ───────────────────────── env generation ─────────────────────────


def gen_password(length: int = 24) -> str:
    return secrets.token_urlsafe(length)[:length]


def gen_jwt_secret() -> str:
    return secrets.token_hex(32)


def write_env(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    info(f"Wrote {path}")


def generate_env_files(install_dir: Path, cfg: dict) -> None:
    """Generate .env, api/.env, worker/.env, mcp/.env consistently."""
    db_user = "kwhale"
    db_name = "kwhale"
    db_pass = cfg["postgres_password"]
    database_url = f"postgresql://{db_user}:{db_pass}@postgres:5432/{db_name}"
    nav_user = cfg["navidrome_username"]
    nav_pass = cfg["navidrome_password"]
    jwt_secret = cfg["jwt_secret"]
    data_root = cfg["data_root"]

    # Root .env (compose substitution)
    write_env(install_dir / ".env", [
        "# KWhale — generated by install.py",
        f"DATA_ROOT={data_root}",
        f"POSTGRES_PASSWORD={db_pass}",
        f"DATABASE_URL={database_url}",
        f"NAVIDROME_USERNAME={nav_user}",
        f"NAVIDROME_PASSWORD={nav_pass}",
        f"YANDEX_MUSIC_TOKEN={cfg.get('yandex_token', '')}",
    ])

    # api/.env
    write_env(install_dir / "api" / ".env", [
        "# KWhale API — generated by install.py",
        f"JWT_SECRET={jwt_secret}",
        f"DATABASE_URL={database_url}",
        "REDIS_URL=redis://redis:6379/0",
        f"OPENAI_API_BASE={cfg['openai_api_base']}",
        f"OPENAI_API_KEY={cfg['openai_api_key']}",
        f"EMBED_MODEL={cfg['embed_model']}",
        f"LLM_MODEL={cfg['llm_model']}",
        f"ICM_PARTNER_KEY={cfg.get('icm_partner_key', '')}",
        "ICM_DEFAULT_REGION=us",
        "ICM_FALLBACK_REGION=ru",
        f"STREAM_AUTO_ACQUIRE_THRESHOLD=3",
        f"YANDEX_MUSIC_TOKEN={cfg.get('yandex_token', '')}",
        f"OMNI_MODEL={cfg.get('omni_model', '')}",
    ])

    # worker/.env
    write_env(install_dir / "worker" / ".env", [
        "# KWhale Worker — generated by install.py",
        f"DATABASE_URL={database_url}",
        "REDIS_URL=redis://redis:6379/0",
        "NAVIDROME_DB=/navidrome/navidrome.db",
        f"YANDEX_MUSIC_TOKEN={cfg.get('yandex_token', '')}",
        f"ICM_PARTNER_KEY={cfg.get('icm_partner_key', '')}",
        "ICM_PARTNER_USER_ID=",
        "ICM_BASE_URL=https://byicloud.online",
        "ICM_REGION=us",
        "ICM_QUALITY=256K",
        f"OPENAI_API_BASE={cfg['openai_api_base']}",
        f"OPENAI_API_KEY={cfg['openai_api_key']}",
        f"EMBED_MODEL={cfg['embed_model']}",
        f"LLM_MODEL={cfg['llm_model']}",
        f"OMNI_MODEL={cfg.get('omni_model', '')}",
    ])

    # mcp/.env
    write_env(install_dir / "mcp" / ".env", [
        "# KWhale MCP — generated by install.py",
        f"DATABASE_URL={database_url}",
        "NAVIDROME_URL=http://navidrome:4533",
        f"NAVIDROME_USERNAME={nav_user}",
        f"NAVIDROME_PASSWORD={nav_pass}",
        "KWHALE_API_URL=http://api:8000",
    ])


# ───────────────────────── docker checks ─────────────────────────


def check_prerequisites() -> None:
    header("Checking prerequisites")
    for tool in ("docker", "git", "python3"):
        if not shutil.which(tool):
            err(f"'{tool}' not found. Please install it first.")
            sys.exit(1)
        info(f"{tool} found")

    # Check docker compose (v2 plugin or standalone)
    try:
        run(["docker", "compose", "version"], check=True, capture=True)
        info("docker compose v2 available")
    except (subprocess.CalledProcessError, FileNotFoundError):
        if shutil.which("docker-compose"):
            warn("Using standalone docker-compose (v1). Consider upgrading to v2.")
        else:
            err("docker compose not found. Install Docker Compose v2.")
            sys.exit(1)

    # Check docker daemon
    try:
        run(["docker", "info"], check=True, capture=True)
        info("Docker daemon running")
    except subprocess.CalledProcessError:
        err("Docker daemon not running. Start it: sudo systemctl start docker")
        sys.exit(1)


def ensure_networks() -> None:
    """Create external networks if they don't exist."""
    header("Ensuring external Docker networks")
    for net in EXTERNAL_NETWORKS:
        try:
            result = run(["docker", "network", "inspect", net], check=False, capture=True)
            if result.returncode == 0:
                info(f"Network '{net}' exists")
            else:
                run(["docker", "network", "create", net])
                info(f"Created network '{net}'")
        except Exception as e:
            warn(f"Could not ensure network '{net}': {e}")


# ───────────────────────── health checks ─────────────────────────


def wait_for_health(install_dir: Path, cfg: dict, timeout: int = 180) -> bool:
    header("Waiting for services to become healthy")
    api_port = cfg["api_port"]
    nav_port = cfg["navidrome_port"]
    api_url = f"http://127.0.0.1:{api_port}/healthz"
    nav_url = f"http://127.0.0.1:{nav_port}/rest/ping.view"

    deadline = time.time() + timeout
    services = {"API": api_url, "Navidrome": nav_url}
    status = {name: False for name in services}

    while time.time() < deadline:
        for name, url in services.items():
            if not status[name]:
                code = http_get(url, timeout=5)
                if code == 200:
                    info(f"{name} healthy (HTTP 200)")
                    status[name] = True
        if all(status.values()):
            return True
        time.sleep(3)

    for name, ok_ in status.items():
        if not ok_:
            err(f"{name} did not become healthy in {timeout}s")
    return False


# ───────────────────────── main flow ─────────────────────────


def interactive_config(args: argparse.Namespace) -> dict:
    header("KWhale Installer — Configuration")

    install_dir = Path(args.install_dir or Path.cwd() / INSTALL_DIR_NAME).resolve()
    data_root = Path(args.data_root or (install_dir.parent / "kwhale-data")).resolve()

    cfg = {
        "install_dir": install_dir,
        "data_root": str(data_root),
        "repo_url": args.repo or DEFAULT_REPO,
        "branch": args.branch or DEFAULT_BRANCH,
        "api_port": args.api_port or 19000,
        "navidrome_port": args.navidrome_port or 4535,
    }

    if args.non_interactive:
        cfg.update({
            "navidrome_username": "admin",
            "navidrome_password": gen_password(),
            "postgres_password": gen_password(),
            "jwt_secret": gen_jwt_secret(),
            "openai_api_base": "https://api.openai.com/v1",
            "openai_api_key": "",
            "embed_model": "text-embedding-3-small",
            "llm_model": "gpt-4o-mini",
            "omni_model": "",
            "icm_partner_key": "",
            "yandex_token": "",
        })
        return cfg

    cfg["navidrome_username"] = prompt("Navidrome admin username", "admin")
    cfg["navidrome_password"] = prompt("Navidrome admin password", gen_password(16), password=True)
    cfg["postgres_password"] = prompt("PostgreSQL password", gen_password(), password=True)
    cfg["jwt_secret"] = gen_jwt_secret()
    info(f"Generated JWT secret ({len(cfg['jwt_secret'])} chars)")

    print()
    print("  AI features need an OpenAI-compatible API (embeddings + LLM).")
    cfg["openai_api_base"] = prompt("OpenAI API base URL", "https://api.openai.com/v1")
    cfg["openai_api_key"] = prompt("OpenAI API key", "", password=True)
    cfg["embed_model"] = prompt("Embedding model", "text-embedding-3-small")
    cfg["llm_model"] = prompt("LLM Model", "gpt-4o-mini")

    print()
    print("  Optional: source plugins (leave blank to skip).")
    cfg["icm_partner_key"] = prompt("ICM Partner Key", "", password=True)
    cfg["yandex_token"] = prompt("Yandex Music Token", "", password=True)
    cfg["omni_model"] = ""

    return cfg


def clone_repo(cfg: dict) -> None:
    install_dir = cfg["install_dir"]
    header(f"Cloning KWhale from {cfg['repo_url']}")

    if install_dir.exists() and (install_dir / ".git").exists():
        info(f"Repo exists at {install_dir}, pulling latest...")
        run(["git", "fetch", "--all"], cwd=install_dir)
        run(["git", "checkout", cfg["branch"]], cwd=install_dir)
        run(["git", "pull", "origin", cfg["branch"]], cwd=install_dir)
    elif install_dir.exists() and any(install_dir.iterdir()):
        err(f"Directory {install_dir} exists and is not empty.")
        sys.exit(1)
    else:
        install_dir.parent.mkdir(parents=True, exist_ok=True)
        run(["git", "clone", "-b", cfg["branch"], cfg["repo_url"], str(install_dir)])
        info(f"Cloned to {install_dir}")


def create_data_dirs(cfg: dict) -> None:
    data_root = Path(cfg["data_root"])
    header(f"Creating data directories at {data_root}")
    for sub in ("music/library", "music/incoming", "music/failed", "navidrome", "postgres", "redis"):
        d = data_root / sub
        d.mkdir(parents=True, exist_ok=True)
    info(f"Data root: {data_root}")


def build_and_start(cfg: dict) -> None:
    install_dir = cfg["install_dir"]
    header("Building Docker images (this may take a while...)")

    # Use compose override to set custom ports if non-default
    if cfg["api_port"] != 19000 or cfg["navidrome_port"] != 4535:
        write_compose_override(install_dir, cfg)

    run(["docker", "compose", "build"], cwd=install_dir)
    info("Build complete")

    header("Starting services")
    run(["docker", "compose", "up", "-d"], cwd=install_dir)
    info("Services started")


def write_compose_override(install_dir: Path, cfg: dict) -> None:
    """Write docker-compose.override.yml for custom ports."""
    override = install_dir / "docker-compose.override.yml"
    lines = [
        "services:",
        "  navidrome:",
        "    ports:",
        f'      - "127.0.0.1:{cfg["navidrome_port"]}:4533"',
        "  api:",
        "    ports:",
        f'      - "127.0.0.1:{cfg["api_port"]}:8000"',
        "  tagger:",
        "    ports:",
        f'      - "127.0.0.1:{cfg["api_port"] + 93}:8093"',
    ]
    write_env(override, lines)
    info(f"Wrote compose override for custom ports")


def get_api_token(cfg: dict) -> str | None:
    header("Getting API token")
    url = f"http://127.0.0.1:{cfg['api_port']}/api/auth/login"
    resp = http_post_json(url, {
        "username": cfg["navidrome_username"],
        "password": cfg["navidrome_password"],
    }, timeout=15)
    if resp and "token" in resp:
        info(f"Login successful, token length: {len(resp['token'])}")
        return resp["token"]
    warn("Could not get API token. You can log in manually later.")
    return None


def offer_first_scan(cfg: dict, token: str | None) -> None:
    if not token:
        return
    if cfg.get("non_interactive"):
        return
    if not confirm("Trigger first library index (audio analysis)?", default=False):
        return
    url = f"http://127.0.0.1:{cfg['api_port']}/api/vibe/index-all"
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            if resp.status == 202:
                info("Indexing started in background. Check: docker compose logs -f worker")
            else:
                warn(f"Index trigger returned {resp.status}")
    except Exception as e:
        warn(f"Could not trigger indexing: {e}")


def print_summary(cfg: dict, token: str | None) -> None:
    header("KWhale is running!")
    print(f"""
  Data root:     {cfg['data_root']}
  Install dir:   {cfg['install_dir']}

  Services:
    API:         http://127.0.0.1:{cfg['api_port']}
    API docs:    http://127.0.0.1:{cfg['api_port']}/docs
    Navidrome:   http://127.0.0.1:{cfg['navidrome_port']}

  Credentials:
    Navidrome:   {cfg['navidrome_username']} / (password you set)
    API token:   {token or '(login manually)'}

  Next steps:
    1. Add music: copy files to {cfg['data_root']}/music/library/
    2. Navidrome auto-scans every 1 minute
    3. Index: curl -X POST http://127.0.0.1:{cfg['api_port']}/api/vibe/index-all \\
         -H "Authorization: Bearer {token or 'TOKEN'}"
    4. Logs:   cd {cfg['install_dir']} && docker compose logs -f worker

  Management:
    python3 {cfg['install_dir'] / 'kwhalectl.py'} status
    python3 {cfg['install_dir'] / 'kwhalectl.py'} smoke
""")


# ───────────────────────── entrypoint ─────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="KWhale one-command installer")
    parser.add_argument("--non-interactive", action="store_true", help="Run without prompts (CI/automated)")
    parser.add_argument("--data-root", help="Data root path (default: ../kwhale-data)")
    parser.add_argument("--install-dir", help="Install directory (default: ./kwhale)")
    parser.add_argument("--repo", help="Git repo URL")
    parser.add_argument("--branch", help="Git branch")
    parser.add_argument("--api-port", type=int, help="API host port (default: 19000)")
    parser.add_argument("--navidrome-port", type=int, help="Navidrome host port (default: 4535)")
    args = parser.parse_args()

    print(r"""
  _  __  _  __   ____  _          __  __
 | |/ / | |/ /  |  _ \| |        |  \/  |
 | ' /  | ' /   | |_) | |        | \  / |
 | . \  | . \   |  _ <| |___     | |\/| |
 |_|\_\ |_|\_\  |_| \_\_____|    |_|  |_|
        Self-hosted music with AI recommendations
""")

    check_prerequisites()
    cfg = interactive_config(args)
    clone_repo(cfg)

    # Re-resolve install_dir in case it was relative
    install_dir = cfg["install_dir"]
    if not (install_dir / "docker-compose.yml").exists():
        err(f"docker-compose.yml not found in {install_dir}")
        sys.exit(1)

    ensure_networks()
    create_data_dirs(cfg)
    generate_env_files(install_dir, cfg)
    build_and_start(cfg)

    if not wait_for_health(install_dir, cfg, timeout=300):
        err("Some services did not become healthy. Check logs:")
        print(f"  cd {install_dir} && docker compose logs")
        sys.exit(1)

    token = get_api_token(cfg)
    offer_first_scan(cfg, token)
    print_summary(cfg, token)


if __name__ == "__main__":
    main()